<#
.SYNOPSIS
    WinMate command line: install, update or remove Windows apps from the WinMate catalog.

.DESCRIPTION
    Uses exactly the same engine as the scripts generated on the website. The app catalog is
    embedded in this file, nothing is downloaded from WinMate and nothing is sent anywhere.
    Only one administrator prompt is shown for all installers.

.EXAMPLE
    .\winmate.ps1 -List -Search browser
    Lists catalog apps that match "browser".

.EXAMPLE
    .\winmate.ps1 -Apps firefox,vlc,7zip -DryRun
    Shows what would be installed without changing anything.

.EXAMPLE
    .\winmate.ps1 -Bundle gaming -RestorePoint
    Installs the Gaming PC bundle with winget after creating a restore point.

.EXAMPLE
    .\winmate.ps1 -ProfilePath .\winmate-profile.json -Mode upgrade
    Updates every app of a profile exported from the website.

.EXAMPLE
    .\winmate.ps1 -Verify .\WinMate-Install.cmd
    Checks that a downloaded script contains the unmodified WinMate engine and lists its apps.

.EXAMPLE
    .\winmate.ps1 -Logs
    Shows the most recent runs, their results, log files and undo scripts.

.LINK
    https://github.com/baba537/WinMate
#>
[CmdletBinding()]
param(
    [string[]]$Apps,
    [string[]]$Bundle,
    [string]$ProfilePath,
    [ValidateSet('winget', 'scoop', 'choco')][string]$PackageManager,
    [ValidateSet('install', 'upgrade', 'uninstall')][string]$Mode = 'install',
    [switch]$DryRun,
    [switch]$RestorePoint,
    [switch]$PinVersions,
    [string]$Proxy = '',
    [switch]$NoPause,
    [string]$ExportScript,
    [switch]$List,
    [string]$Search,
    [switch]$Bundles,
    [switch]$Logs,
    [string]$Verify,
    [switch]$Version
)

$ErrorActionPreference = 'Stop'
$WinMateVersion = '__WINMATE_VERSION__'
$EngineSha256 = '__ENGINE_SHA256__'
$SiteUrl = '__SITE_URL__'
$Catalog = @'
__CATALOG_JSON__
'@ | ConvertFrom-Json
$EngineText = @'
__ENGINE_TEXT__
'@

function Get-Sha256Hex([string]$Text) {
    $sha = [Security.Cryptography.SHA256]::Create()
    ($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($Text)) | ForEach-Object { $_.ToString('x2') }) -join ''
}
function ConvertTo-PsLiteral([string]$Value) { "'" + ($Value -replace "'", "''") + "'" }

# Line endings may change when the file is checked out or downloaded; the hash is defined over LF.
$EngineText = $EngineText.Replace("`r`n", "`n").TrimEnd()
if ((Get-Sha256Hex $EngineText) -ne $EngineSha256) {
    Write-Host 'The embedded WinMate engine does not match its SHA-256 hash. This file was modified.' -ForegroundColor Red
    exit 3
}

if ($Version) {
    Write-Host "WinMate $WinMateVersion"
    Write-Host "Engine SHA-256: $EngineSha256"
    exit 0
}

# --- Verify a downloaded script ---------------------------------------------------
if ($Verify) {
    $text = (Get-Content -LiteralPath $Verify -Raw -Encoding UTF8).Replace("`r`n", "`n")
    $engine = [regex]::Match($text, '(?s)\n[ \t]*# >>> engine\n(.*?)\n[ \t]*# <<< engine')
    if (-not $engine.Success) {
        Write-Host 'No WinMate engine block found in this file.' -ForegroundColor Red
        exit 2
    }
    $hash = Get-Sha256Hex $engine.Groups[1].Value.TrimEnd()
    $header = [regex]::Match($text, '#\s+WinMate (\S+)')
    Write-Host "File:                $Verify"
    if ($header.Success) { Write-Host "Generated by:        WinMate $($header.Groups[1].Value)" }
    Write-Host "Engine in file:      $hash"
    Write-Host "Engine of $($WinMateVersion.PadRight(9)): $EngineSha256"
    $config = [regex]::Match($text, '(?s)# >>> config\n(.*?)\n[ \t]*# <<< config')
    if ($config.Success) {
        Write-Host ''
        Write-Host 'Configuration (this is what the script will do):' -ForegroundColor Cyan
        Write-Host $config.Groups[1].Value
    }
    Write-Host ''
    if ($hash -eq $EngineSha256) {
        Write-Host 'OK - the engine is the unmodified WinMate engine.' -ForegroundColor Green
        exit 0
    }
    Write-Host 'MISMATCH - the engine differs from this WinMate version.' -ForegroundColor Red
    Write-Host 'Either the script was modified, or it was generated by another WinMate version.' -ForegroundColor Yellow
    Write-Host 'Compare with the engine hash published in that version''s GitHub release.' -ForegroundColor Yellow
    exit 1
}

# --- Run history -------------------------------------------------------------------
if ($Logs) {
    $runDir = Join-Path $env:LOCALAPPDATA 'WinMate\runs'
    $runs = @(Get-ChildItem -Path $runDir -Filter '*.json' -ErrorAction SilentlyContinue | Sort-Object Name -Descending)
    if (-not $runs.Count) { Write-Host "No runs recorded yet ($runDir)."; exit 0 }
    $records = @($runs | Select-Object -First 15 | ForEach-Object { Get-Content $_.FullName -Raw -Encoding UTF8 | ConvertFrom-Json })
    $records | ForEach-Object {
        [pscustomobject]@{
            Run = $_.id; Mode = $(if ($_.dryRun) { "$($_.mode) (dry run)" } else { $_.mode }); Manager = $_.packageManager
            Apps = @($_.results).Count; Failed = @($_.results | Where-Object { $_.Status -eq 'failed' }).Count
        }
    } | Format-Table -AutoSize
    $latest = $records[0]
    Write-Host "Latest run $($latest.id):" -ForegroundColor Cyan
    $latest.results | Format-Table Name, Id, Status, Code, Detail -AutoSize
    Write-Host "Log file:    $($latest.log)"
    $undo = Join-Path $runDir "$($latest.id)-undo.ps1"
    if (Test-Path $undo) { Write-Host "Undo script: $undo" }
    exit 0
}

# --- Catalog browsing --------------------------------------------------------------
if ($List -or $Search) {
    $items = @($Catalog.apps)
    if ($Search) { $items = @($items | Where-Object { "$($_.id) $($_.name) $($_.category) $($_.description)" -like "*$Search*" }) }
    $items | Select-Object @{ n = 'Id'; e = { $_.id } }, @{ n = 'Name'; e = { $_.name } }, @{ n = 'Category'; e = { $_.category } },
        @{ n = 'winget'; e = { [bool]$_.winget } }, @{ n = 'Scoop'; e = { [bool]$_.scoop } }, @{ n = 'Chocolatey'; e = { [bool]$_.choco } } |
        Format-Table -AutoSize
    Write-Host "$($items.Count) app(s). Install with: .\winmate.ps1 -Apps <id>,<id>"
    exit 0
}
if ($Bundles) {
    $Catalog.bundles | Select-Object @{ n = 'Id'; e = { $_.id } }, @{ n = 'Name'; e = { $_.name } }, @{ n = 'Apps'; e = { $_.apps -join ', ' } } |
        Format-Table -Wrap -AutoSize
    exit 0
}

# --- Resolve the selection ---------------------------------------------------------
$byId = @{}
foreach ($a in $Catalog.apps) { $byId[$a.id] = $a }
$selected = New-Object System.Collections.Generic.List[string]
function Add-Id([string]$Id) { $Id = $Id.Trim(); if ($Id -and -not $selected.Contains($Id)) { $selected.Add($Id) } }
function Get-BundleApps([string]$Id) {
    $b = @($Catalog.bundles | Where-Object { $_.id -eq $Id })
    if (-not $b.Count) { throw "Unknown bundle '$Id'. Use -Bundles to list them." }
    return @($b[0].apps)
}

$pm = $PackageManager
if ($ProfilePath) {
    $profileData = Get-Content -LiteralPath $ProfilePath -Raw -Encoding UTF8 | ConvertFrom-Json
    if (-not $pm -and $profileData.pm) { $pm = $profileData.pm }
    foreach ($id in @($profileData.manual)) { if ($id) { Add-Id $id } }
    foreach ($b in @($profileData.bundles)) {
        if ($b) { foreach ($id in Get-BundleApps $b) { if (@($profileData.excluded) -notcontains $id) { Add-Id $id } } }
    }
}
foreach ($b in @($Bundle)) { if ($b) { foreach ($id in Get-BundleApps $b) { Add-Id $id } } }
foreach ($a in @($Apps)) { if ($a) { foreach ($id in $a -split ',') { Add-Id $id } } }
if (-not $pm) { $pm = 'winget' }

if (-not $selected.Count) {
    Write-Host 'Nothing selected. Use -Apps, -Bundle or -ProfilePath. Try -List, -Bundles or Get-Help .\winmate.ps1 -Examples.' -ForegroundColor Yellow
    exit 1
}
$unknown = @($selected | Where-Object { -not $byId.ContainsKey($_) })
if ($unknown.Count) {
    foreach ($u in $unknown) {
        $hint = @($Catalog.apps.id | Where-Object { $_ -like "*$u*" } | Select-Object -First 5) -join ', '
        Write-Host "Unknown app '$u'.$(if ($hint) { " Did you mean: $hint" })" -ForegroundColor Red
    }
    exit 1
}

# Runtimes first, so apps that depend on them install cleanly.
$ordered = @($selected | Where-Object { $byId[$_].category -eq 'runtimes' }) + @($selected | Where-Object { $byId[$_].category -ne 'runtimes' })
$entries = @()
$buckets = @()
$skipped = @()
foreach ($id in $ordered) {
    $app = $byId[$id]
    switch ($pm) {
        'winget' {
            if (-not $app.winget) { $skipped += $app.name; continue }
            $ids = @($app.winget)
            foreach ($wid in $ids) {
                $store = $wid.StartsWith('msstore:')
                $name = if ($ids.Count -gt 1) { "$($app.name -replace '\s*\(.*\)$', '') - $wid" } else { $app.name }
                $parts = @("Name = $(ConvertTo-PsLiteral $name)", "Id = $(ConvertTo-PsLiteral $(if ($store) { $wid.Substring(8) } else { $wid }))")
                if ($store) { $parts += "Source = 'msstore'" }
                if ($app.noAdmin) { $parts += 'NoAdmin = $true' }
                if ($PinVersions -and $app.wv -and $app.wv.$wid) { $parts += "Version = $(ConvertTo-PsLiteral $app.wv.$wid)" }
                $entries += "        @{ $($parts -join '; ') }"
            }
        }
        'scoop' {
            if (-not $app.scoop) { $skipped += $app.name; continue }
            $bucket = $app.scoop.Split('/')[0]
            if ($bucket -ne 'main' -and $buckets -notcontains $bucket) { $buckets += $bucket }
            $entries += "        @{ Name = $(ConvertTo-PsLiteral $app.name); Id = $(ConvertTo-PsLiteral $app.scoop) }"
        }
        'choco' {
            if (-not $app.choco) { $skipped += $app.name; continue }
            $parts = @("Name = $(ConvertTo-PsLiteral $app.name)", "Id = $(ConvertTo-PsLiteral $app.choco)")
            if ($PinVersions -and $app.cv) { $parts += "Version = $(ConvertTo-PsLiteral $app.cv)" }
            $entries += "        @{ $($parts -join '; ') }"
        }
    }
}
if ($skipped.Count) { Write-Host "Not available for ${pm}, skipped: $($skipped -join ', ')" -ForegroundColor Yellow }
if (-not $entries.Count) { Write-Host "None of the selected apps is available for $pm." -ForegroundColor Red; exit 1 }

$label = @{ install = 'install'; upgrade = 'update'; uninstall = 'uninstall' }[$Mode]
$lines = @(
    '# ============================================================================',
    "#  WinMate $WinMateVersion $label script - $SiteUrl",
    "#  Generated $(Get-Date -Format 'yyyy-MM-dd') by winmate.ps1 - $($entries.Count) package(s) with $pm$(if ($DryRun) { ' (dry run)' })",
    "#  Engine SHA-256: $EngineSha256",
    "#  Verify: winmate.ps1 -Verify <file>   Details: $SiteUrl/security/",
    '# ============================================================================',
    '& {',
    '    param([string]$Phase, [string]$ResultFile, [switch]$NoPause, [string]$RunId)',
    '    # >>> config',
    "    `$PackageManager = $(ConvertTo-PsLiteral $pm)",
    "    `$Mode = $(ConvertTo-PsLiteral $Mode)",
    "    `$DryRun = $(if ($DryRun) { '$true' } else { '$false' })",
    "    `$RestorePoint = $(if ($RestorePoint) { '$true' } else { '$false' })",
    "    `$Proxy = $(ConvertTo-PsLiteral $Proxy)",
    "    `$Buckets = @($(($buckets | ForEach-Object { ConvertTo-PsLiteral $_ }) -join ', '))",
    '    $Apps = @('
) + $entries + @(
    '    )',
    '    # <<< config',
    '    # >>> engine',
    $EngineText,
    '    # <<< engine',
    '}'
)
$scriptText = ($lines -join "`n") + "`n"

if ($ExportScript) {
    [IO.File]::WriteAllText($ExportScript, $scriptText, (New-Object Text.UTF8Encoding $true))
    Write-Host "Saved $ExportScript"
    exit 0
}

$run = $scriptText.TrimEnd() + $(if ($NoPause) { ' -NoPause' } else { '' })
& ([ScriptBlock]::Create($run))
